---
layout: default
description: Harrison Bergeron
---
# Harrison Bergeron by Kurt Vonnegut
### Date added: 2022/04/10

Once the 31st president of the United states said that “Freedom is the open window through which pours the sunlight of the human spirit and human dignity.” Freedom should not be given to select people, as the First Amendment of the United States established that everyone is entitled to certain types of freedom. “Harrison Bergeron,” a short story by Kurt Vonnegut from the early 1960s, depicts a society where the government enforces total equality to a point of absurdity. Even with the story being over exaggerated, it illustrates the consequences that a society may face when venturing in progressivism. Vonnegut warns the reader that extremism can render a well-intentioned paradise into a living hell.
	Almost everyone would agree that equality for all should be the goal of any enlightened society, yet “There is no such thing as free lunch,” Nobel prize Laureate Milton Friedman once said. Everything has a cost, and even if it seems free at first, strings will most likely be attached. Vonnegut highlights this point with the title character's parents. His mother suffers from “average IQ” and EQ, in which she inadvertently suggests that “...it would be [really] interesting, hearing all the different sounds… All the things they think up” (Vonnegut). She remains oblivious as to the complete insensitivity to her husband's plight and thinks it amusing to hear those ear splitting, mind crushing noises. His father, “George [on the other hand, his] intelligence was way above normal, [he] had a little mental handicap radio in his ear” (Vonnegut). Society punished him for his intellect and greater stature to level the playing field in society. In essence, when the sounds go off, the government reduces him to an imbecile. 
Furthermore, Thomas Draxe once said “like father like son.” This quote accurately depicts Harrison, as he is just like his father, but better in every perspective: he stands taller, thinks smarter, and more handsome. When Harrison decides to revolt against the government and their self imposed “equality”, he decided to “[tear] the straps of his handicap harness like wet tissue paper, [he] tore straps guaranteed to support five thousand pounds. Harrison’s scrap-iron handicaps crashed to the floor” (Vonnegut). As can be seen, everybody within the story of “Harrison Bergeron” is made equal, but not with genetic engineering. This hodge podge of torture and discomforts becomes the truth and norm to those people who repel competition, which nature installed in everyone. The government is trying to use Walmart hardware and sound bites to create a divine culture but the reader will have realized that this story is as dystopian as it gets. Vonnergut attempts to validate the old adage: “Be careful what you wish for; you might just get it.” A healthy society would certainly function better with equal opportunities, but true equality in every regard remains elusive and almost impossible, given the characteristics that nature endows individuals with.
The saying “too much of anything is a bad thing” applies to everything within life, including many things that people believe will “fix” their societies. Kurt Vonegut demonstrates how a society with good intentions will sooner or later become an extreme mockery of the original goal, thereby creating a dystopia. In life, some of the easiest solutions may not be the correct ones. Profound thought about results and consequences always needs to figure into any societal change to avoid hardship and pain, afflicting those who the government are sworn to protect. 

http://issaquahhighkdean.weebly.com/uploads/8/3/2/6/83262826/harrison_bergeron.pdf