layout: default
description: George Orwell Animal Farm: Three Significant Events
---
# Animal Farm by George Orwell
### Date added: 2022/12/1
Many plot developments within the same story leave a lasting image in the reader’s mind, and one can define these as main events. The climax of any story enhances the impact that it gives the reader. George Orwell’s Animal Farm offers many intriguing moments that change the course of events for the characters in this communist allegory, most notably Animal Farm’s establishment, Snowball’s expulsion, and Boxer’s horrendous death.
 
Every country or establishment needs rules, for without them, disarray, chaos or entropy may ensue. All of the animals, in unanimous body and voice, established Animal Farm following their revolt against farmer Jones’s men. Upon their independence, in the form of a fledgling democracy, they enacted the seven commandments that declared, “Whatever goes on two legs is an enemy. Whatever goes upon four legs, or has wings is a friend. No animal shall wear clothes. No animals shall sleep in a bed. No animal shall drink alcohol. No animal shall kill any animal. All animals are equal” (Orwell 25). So what this means is:  These regulations, just as with the glorious revolution in Russia, where Lenin usurped power from the Czars, the animals took control of their destiny by creating a government for the animals, by the animals. Like all beginning, idealistic republics, they paved their road to glory with good intentions. Yet, every good, conscientious system of merit seldom lasts, as the idea of equality slowly, but surely, deteriorates and the affluent, with their corruption, take over.  
 
Opposing sides of differing ideology would naturally seek the destruction of the other so their rule goes unchallenged. In the story, the expulsion of Snowball signified the end of a democracy on Animal Farm, and the beginning of dictatorship. In Chapter 6, Snowball told the animals the plans of building a windmill, but in describing the reaction to the divulging of the plans, Orwell writes, “[Napoleon] “stood up and, casting a peculiar sidelong look at Snowball, uttered a high-pitched whimper… and… nine enormous dogs wearing brass-studded collars came into the barn. They dashed straight for Snowball … [after an intense chase, Snowball] slipped through a hole in the hedge [of the farm] and was seen no more” (Orwell 53). Napoleon, instead of his usual disagreement with the idea, used brute force to deny Snowball’s proposal. However, as the reader would find out, as Orwell writes, “[Napoleon] did not contradict the idea of a windmill, but he simply did it as a [maneuver] to get rid of Snowball, who was a dangerous character and had a bad influence” (Orwell 58). In the absence of a contradiction, Napoleon began progressively brainwashing the animals so he and his drove could assert their authority over the less intelligent animals. Snowball’s hasty departure left the animals vulnerable to the lies of Squealer and Napoleon (as is evident throughout the last few chapters). One can see the gaslighting in full effect, especially during the supposed treatment of Boxer in Willingdon. 
 
 	People who earn respect can serve as role models. They have the ability to influence through their hard work, or through their words. All the animals admire Boxer for his iron will and resilience during hardship. During Chapter 9 of Animal Farm, Boxer had collapsed from overwork and stood at death’s door. Napoleon, after hearing about Boxer’s condition, promised that he would send Boxer to a hospital, as the “veterinary surgeon in Willingdon could treat Boxer’s case more satisfactorily than could be done on the farm,” which the animals thought logical (Orwell 120). However, when the animals came to see Boxer get taken to the supposed hospital, Benjamin exclaimed, “Fools! Do you not see what is written on the side of that van... Alfred Simonds, Horse Slaughtered and Glue Boiler, Willingdon. Dealer in Hides and Bonemeal. Kennels Supplied.’ Do you not understand what that means? They are taking Boxer to the knacker’s” (Orwell 122). However, when Squealer came to announce the death of Boxer in the hospital, he also addressed the rumor that Boxer had been sent to the knackers by berating the doubters, asking how “any animal could be so stupid... surely, [the animals knew] that their beloved Leader, Comrade Napoleon, better than that” (Orwell 124-25). Boxer’s admirable pouring of his blood and sweat into the benefit of Animal Farm impacts the reader and brings about the gratitude of all animals, yet the pigs sold him off once he was no longer of value to the pigs. Furthermore, the authoritarians swindled the other animals into believing that Boxer had died at a hospital instead of being sent to the “knackers” (Orwell 122). Even though Boxer dedicated his life to the farm, the pigs had sold him off so they could purchase more alcohol to feed their addiction, thereby revealing the true nature of the pigs, who are willing to exploit and brainwash others for their gain and dispose of the ones who have no more value to them.
 
Life offers individuals many events that impact their lives. Some remain within their control, and others lie beyond it. George Orwell’s Animal Farm provides the reader with several important moments that alter the story’s development through the creation of Animal Farm, the loss of a voice for the people, and gaslighting to convince the masses. Orwell’s vision of the rise of authoritarian regimes may give insight on the events that one may encounter in contemporary political systems. He demonstrates the fragility of a democracy when a strong hand and voice strong arms the people into submission. 